### ISSUE TITLE
Miscompilation of `std::thread::scope` on x86_64 with llvm sysroot

### ISSUE THREAD

**Issue by bjorn3** [rust-lang/rustc_codegen_cranelift#1395]
```rust
fn main() {
    std::thread::scope(|s| {
        s.spawn(|| {});
    });
}
```

```
$ ./y.sh build --sysroot llvm
$ dist/bin/rustc-clif foo.rs
$ RUST_BACKTRACE=1 ./foo
```

```
thread 'main' panicked at foo.rs:2:5:
a scoped thread panicked
stack backtrace:
   0: rust_begin_unwind
             at /rustc/65ea825f4021eaf77f1b25139969712d65b435a4/library/std/src/panicking.rs:619:5
   1: core::panicking::panic_fmt
             at /rustc/65ea825f4021eaf77f1b25139969712d65b435a4/library/core/src/panicking.rs:72:14
   2: std::thread::scoped::scope
   3: foo::main
   4: core::ops::function::FnOnce::call_once
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Aborted (core dumped)
```

**Comment by bjorn3** [comment]
This blocks an update of the regex version we test.

**Comment by bjorn3** [comment]
Somewhat reduced version:

```
fn main() {
    std::thread::scope(|s| {
        std::thread::Builder::new().spawn_scoped(s, || {}).expect("failed to spawn thread");
    });
}
```

**Comment by bjorn3** [comment]
https://github.com/bytecodealliance/wasmtime/issues/7210 seems to be the root cause of this.
