### ISSUE TITLE
Cranelift compilation failing

### ISSUE THREAD

**Issue by krazyuniks** [rust-lang/rustc_codegen_cranelift#1478]
Some crates aren't building, this started a week or so ago. This example includes a single crate async-trait but also fails with other traits such as axum. Other projects do build. The error does not happen when using nightly without cranelift.

### Code

```Rust
fn main() {
    println!("Hello, world!");
}
```

### Meta
`rustc --version --verbose`:
```
rustc 1.79.0-nightly (4fd4797c2 2024-04-03)
binary: rustc
commit-hash: 4fd4797c2654977f545c9a91e2aa4e6cdbb38919
commit-date: 2024-04-03
host: x86_64-unknown-linux-gnu
release: 1.79.0-nightly
LLVM version: 18.1.2
```

### Error output

```
   Compiling unicode-ident v1.0.12
   Compiling proc-macro2 v1.0.79
thread 'rustc' panicked at src/num.rs:134:9:
assertion `left == right` failed: int binop requires lhs and rhs of same type
  left: u8
 right: u32
stack backtrace:
   0:     0x725c0ddc6ab5 - std::backtrace_rs::backtrace::libunwind::trace::hba9744a938fbd99d
                               at /rustc/4fd4797c2654977f545c9a91e2aa4e6cdbb38919/library/std/src/../../backtrace/src/backtrace/libunwind.rs:105:5
   1:     0x725c0ddc6ab5 - std::backtrace_rs::backtrace::trace_unsynchronized::h3a2e7108b86b8924
                               at /rustc/4fd4797c2654977f545c9a91e2aa4e6cdbb38919/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x725c0ddc6ab5 - std::sys_common::backtrace::_print_fmt::h3a6cfbae8221b005
                               at /rustc/4fd4797c2654977f545c9a91e2aa4e6cdbb38919/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x725c0ddc6ab5 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h9ca10d4d97dfbf60
                               at /rustc/4fd4797c2654977f545c9a91e2aa4e6cdbb38919/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x725c0de15d0b - core::fmt::rt::Argument::fmt::hb38b7803d8fbf2a9
                               at /rustc/4fd4797c2654977f545c9a91e2aa4e6cdbb38919/library/core/src/fmt/rt.rs:142:9
   5:     0x725c0de15d0b - core::fmt::write::h6b7f853053adddb6
                               at /rustc/4fd4797c2654977f545c9a91e2aa4e6cdbb38919/library/core/src/fmt/mod.rs:1153:17
   6:     0x725c0ddbb71f - std::io::Write::write_fmt::hde1e35e2fc064f95
                               at /rustc/4fd4797c2654977f545c9a91e2aa4e6cdbb38919/library/std/src/io/mod.rs:1843:15
   7:     0x725c0ddc688e - std::sys_common::backtrace::_print::h4dd5f8979d76d49c
                               at /rustc/4fd4797c2654977f545c9a91e2aa4e6cdbb38919/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x725c0ddc688e - std::sys_common::backtrace::print::hfe97bcdddb82ade7
                               at /rustc/4fd4797c2654977f545c9a91e2aa4e6cdbb38919/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x725c0ddc92d9 - std::panicking::default_hook::{{closure}}::h632142882587e5b1
  10:     0x725c0ddc9043 - std::panicking::default_hook::hfd47c2bd9a787ae3
                               at /rustc/4fd4797c2654977f545c9a91e2aa4e6cdbb38919/library/std/src/panicking.rs:291:9
  11:     0x725c0a7f7d5e - std[92a9a0c9ca3eface]::panicking::update_hook::<alloc[f20f85c149f776b2]::boxed::Box<rustc_driver_impl[fad2ca4cadd64c2c]::install_ice_hook::{closure#0}>>::{closure#0}
  12:     0x725c0ddc99dc - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hd1914707f70617da
                               at /rustc/4fd4797c2654977f545c9a91e2aa4e6cdbb38919/library/alloc/src/boxed.rs:2032:9
  13:     0x725c0ddc99dc - std::panicking::rust_panic_with_hook::hd4eb87c015b3b6b4
                               at /rustc/4fd4797c2654977f545c9a91e2aa4e6cdbb38919/library/std/src/panicking.rs:792:13
  14:     0x725c0ddc9786 - std::panicking::begin_panic_handler::{{closure}}::h07b4a7d39602845d
                               at /rustc/4fd4797c2654977f545c9a91e2aa4e6cdbb38919/library/std/src/panicking.rs:657:13
  15:     0x725c0ddc6f79 - std::sys_common::backtrace::__rust_end_short_backtrace::h5fec33cfc7c51449
                               at /rustc/4fd4797c2654977f545c9a91e2aa4e6cdbb38919/library/std/src/sys_common/backtrace.rs:171:18
  16:     0x725c0ddc94b7 - rust_begin_unwind
                               at /rustc/4fd4797c2654977f545c9a91e2aa4e6cdbb38919/library/std/src/panicking.rs:645:5
  17:     0x725c0de121a6 - core::panicking::panic_fmt::hd6539c62a2ef69d4
                               at /rustc/4fd4797c2654977f545c9a91e2aa4e6cdbb38919/library/core/src/panicking.rs:72:14
  18:     0x725c0de1276f - core::panicking::assert_failed_inner::h7fe8d4c9b23c3949
                               at /rustc/4fd4797c2654977f545c9a91e2aa4e6cdbb38919/library/core/src/panicking.rs:397:23
  19:     0x725bfd7c4c8f - core[41c2f7771ee504b7]::panicking::assert_failed::<rustc_middle[bc908219bd555002]::ty::Ty, rustc_middle[bc908219bd555002]::ty::Ty>
  20:     0x725bfd8553df - rustc_codegen_cranelift[e3b8be16607ab088]::num::codegen_int_binop
  21:     0x725bfd80c3ab - rustc_codegen_cranelift[e3b8be16607ab088]::base::codegen_fn_body
  22:     0x725bfd828b8d - rustc_codegen_cranelift[e3b8be16607ab088]::driver::aot::module_codegen::{closure#0}
  23:     0x725bfd824f37 - rustc_codegen_cranelift[e3b8be16607ab088]::driver::aot::module_codegen
  24:     0x725bfd832229 - rustc_codegen_cranelift[e3b8be16607ab088]::driver::aot::run_aot
  25:     0x725bfd8610a1 - <rustc_codegen_cranelift[e3b8be16607ab088]::CraneliftCodegenBackend as rustc_codegen_ssa[4e5dad7923f53eff]::traits::backend::CodegenBackend>::codegen_crate
  26:     0x725c0ca5545f - rustc_interface[c5dbac1485b725b8]::passes::start_codegen
  27:     0x725c0ca54ad8 - <rustc_interface[c5dbac1485b725b8]::queries::Queries>::codegen_and_build_linker
  28:     0x725c0c8434d3 - rustc_interface[c5dbac1485b725b8]::interface::run_compiler::<core[41c2f7771ee504b7]::result::Result<(), rustc_span[d2e6fbfc0de2a1c0]::ErrorGuaranteed>, rustc_driver_impl[fad2ca4cadd64c2c]::run_compiler::{closure#0}>::{closure#0}
  29:     0x725c0c910213 - std[92a9a0c9ca3eface]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[c5dbac1485b725b8]::util::run_in_thread_with_globals<rustc_interface[c5dbac1485b725b8]::util::run_in_thread_pool_with_globals<rustc_interface[c5dbac1485b725b8]::interface::run_compiler<core[41c2f7771ee504b7]::result::Result<(), rustc_span[d2e6fbfc0de2a1c0]::ErrorGuaranteed>, rustc_driver_impl[fad2ca4cadd64c2c]::run_compiler::{closure#0}>::{closure#0}, core[41c2f7771ee504b7]::result::Result<(), rustc_span[d2e6fbfc0de2a1c0]::ErrorGuaranteed>>::{closure#0}, core[41c2f7771ee504b7]::result::Result<(), rustc_span[d2e6fbfc0de2a1c0]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[41c2f7771ee504b7]::result::Result<(), rustc_span[d2e6fbfc0de2a1c0]::ErrorGuaranteed>>
  30:     0x725c0c910021 - <<std[92a9a0c9ca3eface]::thread::Builder>::spawn_unchecked_<rustc_interface[c5dbac1485b725b8]::util::run_in_thread_with_globals<rustc_interface[c5dbac1485b725b8]::util::run_in_thread_pool_with_globals<rustc_interface[c5dbac1485b725b8]::interface::run_compiler<core[41c2f7771ee504b7]::result::Result<(), rustc_span[d2e6fbfc0de2a1c0]::ErrorGuaranteed>, rustc_driver_impl[fad2ca4cadd64c2c]::run_compiler::{closure#0}>::{closure#0}, core[41c2f7771ee504b7]::result::Result<(), rustc_span[d2e6fbfc0de2a1c0]::ErrorGuaranteed>>::{closure#0}, core[41c2f7771ee504b7]::result::Result<(), rustc_span[d2e6fbfc0de2a1c0]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[41c2f7771ee504b7]::result::Result<(), rustc_span[d2e6fbfc0de2a1c0]::ErrorGuaranteed>>::{closure#1} as core[41c2f7771ee504b7]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  31:     0x725c0ddd33fb - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h2e19bec40cb63999
                               at /rustc/4fd4797c2654977f545c9a91e2aa4e6cdbb38919/library/alloc/src/boxed.rs:2018:9
  32:     0x725c0ddd33fb - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::he36b8da4bff43b93
                               at /rustc/4fd4797c2654977f545c9a91e2aa4e6cdbb38919/library/alloc/src/boxed.rs:2018:9
  33:     0x725c0ddd33fb - std::sys::pal::unix::thread::Thread::new::thread_start::h6b09958d0e879109
                               at /rustc/4fd4797c2654977f545c9a91e2aa4e6cdbb38919/library/std/src/sys/pal/unix/thread.rs:108:17
  34:     0x725c07497b5a - start_thread
                               at ./nptl/pthread_create.c:444:8
  35:     0x725c075285fc - __GI___clone3
                               at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:78
  36:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please attach the file at `/home/ryan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/unicode-ident-1.0.12/rustc-ice-2024-04-04T10_44_22-22409.txt` to your bug report

note: compiler flags: --crate-type lib -C embed-bitcode=no -Z codegen-backend=cranelift -C linker=/usr/bin/clang -C link-arg=--ld-path=/usr/bin/mold

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
stmt _0 = ShrUnchecked(_1, _3)
fn core::num::<impl u8>::wrapping_shr(_1: u8, _2: u32) -> u8 {
    debug self => _1;
    debug rhs => _2;
    let mut _0: u8;
    let mut _3: u32;
    scope 1 (inlined core::num::<impl u8>::unchecked_shr) {
        debug self => _1;
        debug rhs => _3;
    }

    bb0: {
        StorageLive(_3);
        _3 = BitAnd(_2, const 7_u32);
        _0 = ShrUnchecked(_1, _3);
        StorageDead(_3);
        return;
    }
}

error: could not compile `unicode-ident` (lib)
warning: build failed, waiting for other jobs to finish...
```

### Cargo.toml

```
[package]
name = "app"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.79"
```

### ~/.cargo/config.toml

```
[build]
jobs = 8                      # number of parallel jobs, defaults to # of CPUs
incremental = true
rustflags = ["-Z", "threads=8"]
target-dir = "/tmp/cargo-target"

[target.x86_64-unknown-linux-gnu]
linker = "/usr/bin/clang"
rustflags = ["-C", "link-arg=--ld-path=/usr/bin/mold"]

[unstable]
gc = true
codegen-backend = true

[profile.dev]
codegen-backend = "cranelift"
```

**Comment by bjorn3** [comment]
This should be fixed with https://github.com/rust-lang/rustc_codegen_cranelift/pull/1476. I haven't synced it back to the rust repo for inclusion in nightly rustc yet.

**Comment by bjorn3** [comment]
Should be fixed with today's nightly.
